---
global:
  scrape_interval: 1s
  evaluation_interval: 1s

rule_files:
- flink.rules.yml

scrape_configs:
- job_name: 'flink'
  metrics_path: '/'
  static_configs:
  - targets: ['jobmanager:9249', 'taskmanager:9249']
