import csv
import random

# id,name,phone,email,cuisine_type,price_range,vat_code

def generate_rest_info():
    '''
    function that chooses random values from the values below and returns a tuple
    that will be added to the table.
    '''
    name_list = ["Urban Bites", "Sunny Side Grill", "Mango Fusion", "Harbor Delights", "Blue Plate", "Spice Haven", "Brick Oven", "Maple Street Cafe", "Golden Wok", "Pasta Palace", "Savor Street", "Ocean View Bistro", "Crispy Crunch", "Lemon Twist", "Gourmet Garden", "The Roaming Fork", "Savory Seasons", "Basil Bliss", "City Grind", "Mosaic Kitchen", "Red Pepper Grill", "Sip & Savor", "Epicurean Edge", "Table Tales", "Wholesome Delights", "Taste Trail", "Crafted Cuisine", "Crisp & Fresh", "Bella Bistro", "Minty Moments", "Copper Kettle", "Chop Chop House", "Urban Harvest", "Twisted Tastes", "Global Gourmet", "Plated Perfection", "Fusion Fare", "Whisk & Ladle", "Zen Zest", "Nectar Nook", "Cheese Please", "Silver Spoon", "Tender Greens", "Eternal Eats", "Salt & Sugar"]
    first_words = [name.split()[0] for name in name_list]
    rest_of_names = [' '.join(name.split()[1:]) for name in name_list]
    first_word = random.choice(first_words)
    name = first_word + ' ' + random.choice(rest_of_names)

    phone = str(random.randint(100000000, 999999999))

    email_list = ["gmail.com", "yahoo.com", "hotmail.com", "outlook.com", "aol.com", "icloud.com", "zoho.com", "protonmail.com", "gmx.com", "mail.com"]
    email = first_word + '@' + random.choice(email_list)

    cusine_type_list = ['italian', 'arabic', 'japanese', 'mexican', 'american', 'thai', 'vegetarian']
    cuisine_type = random.choice(cusine_type_list)

    price_range_list = ['$', '$$', '$$$', '$$$$']
    price_range = random.choice(price_range_list)

    vat_code = random.randint(10000000, 99999999)

    return (name,phone,email,cuisine_type,price_range,vat_code) #tuple to be added on the table

def generate_rest_infos(num_lines):
    '''
    function that create a list with sample tuples generated by the function generate_rest_info()
    you can set the number you want for the number of lines
    '''
    addresses = []
    i = 1
    for _ in range(num_lines):
        address = generate_rest_info()
        addresses.append((i,) + address)
        i += 1

    return addresses

def save_to_csv(addresses, filename):
    '''
    function that saves the list of tuples in a csv file
    '''
    with open(filename, mode='w', newline='') as file:
        writer = csv.writer(file)
        writer.writerow('id,name,phone,email,cuisine_type,price_range,vat_code'.split(','))
        writer.writerows(addresses)

number_of_restaurants = 10000 #set the number of restaurants you want
num_lines = 10000 #set the number of lines you want
addresses = generate_rest_infos(num_lines)
save_to_csv(addresses, '../../restaurant_info.csv')
