import csv
import random


# restaurant_id,street,address_number,zip_code,city,province,country

def generate_address():
    '''
    function that chooses random values from the lists below and returns a tuple
    that will be added to the table.
    '''
    street_names = ["Via Roma", "Viale Milano", "Corso Venezia", "Via Dante", "Via Garibaldi", "Vicolo delle Erbe", "Piazza del Popolo", "Corso Umberto I", "Via della Repubblica", "Via XX Settembre", "Via Manzoni", "Via Montenapoleone", "Viale Ceccarini", "Vicolo Stretto", "Piazza San Marco", "Corso Vittorio Emanuele", "Via Cavour", "Via della Croce", "Via dei Condotti", "Via Margutta", "Viale dei Traghetti", "Via Flaminia", "Corso Buenos Aires", "Viale Trastevere", "Via del Corso", "Vicolo Fiori", "Via della Moscova", "Via della Mosca", "Piazza Navona", "Viale dei Mille", "Via Appia Antica", "Corso Magenta", "Via Tiburtina", "Viale delle Milizie", "Via dei Fori Imperiali", "Viale dei Colli Portuensi", "Via dei Greci", "Corso Garibaldi", "Viale Parioli", "Via dei Serpenti", "Piazza di Spagna", "Via Giulia", "Vicolo delle Palle", "Via Panisperna", "Corso Italia", "Via del Tritone", "Viale dell'Arte", "Via della Fortezza"]
    street_number = random.randint(1, 200)
    zip_codes = [10001, 90001, 60601, 77001, 85001, 46731, 20158, 2374, 69696]
    cities = ["Rome", "Milan", "Naples", "Turin", "Palermo", "Genoa", "Bologna", "Florence", "Bari", "Catania", "Venice", "Verona", "Messina", "Padua", "Trieste", "Brescia", "Taranto", "Prato", "Modena", "Reggio Calabria", "Reggio Emilia", "Perugia", "Livorno", "Cagliari", "Foggia", "Ravenna", "Rimini", "Salerno", "Ferrara", "Sassari", "Latina", "Giugliano in Campania", "Monza", "Siracusa", "Pescara", "Bergamo", "Forlì", "Trento", "Vicenza", "Terni", "Bolzano", "Novara", "Piacenza", "Ancona", "Andria", "Udine", "Arezzo", "Cesena"]
    states = {"Rome": "RM", "Milan": "MI", "Naples": "NA", "Turin": "TO", "Palermo": "PA", "Genoa": "GE", "Bologna": "BO", "Florence": "FI", "Bari": "BA", "Catania": "CT", "Venice": "VE", "Verona": "VR", "Messina": "ME", "Padua": "PD", "Trieste": "TS", "Brescia": "BS", "Taranto": "TA", "Prato": "PO", "Modena": "MO", "Reggio Calabria": "RC", "Reggio Emilia": "RE", "Perugia": "PG", "Livorno": "LI", "Cagliari": "CA", "Foggia": "FG", "Ravenna": "RA", "Rimini": "RN", "Salerno": "SA", "Ferrara": "FE", "Sassari": "SS", "Latina": "LT", "Giugliano in Campania": "NA", "Monza": "MB", "Siracusa": "SR", "Pescara": "PE", "Bergamo": "BG", "Forlì": "FC", "Trento": "TN", "Vicenza": "VI", "Terni": "TR", "Bolzano": "BZ", "Novara": "NO", "Piacenza": "PC", "Ancona": "AN", "Andria": "BT", "Udine": "UD", "Arezzo": "AR", "Cesena": "FC"}


    street_name = random.choice(street_names)
    city = random.choice(cities)
    state = states[city]
    zip_code = random.choice(zip_codes)

    return (street_name,street_number,zip_code, city,state, 'Italy') #tuple

def generate_addresses(num_addresses):
    '''
    function that create a list with sample tuples generated by the function generate_address()
    you can set the number you want for the number of lines
    '''
    addresses = []
    i = 1
    for _ in range(num_addresses):
        address = generate_address()
        addresses.append((i,) + address)
        i += 1

    return addresses

def save_to_csv(addresses, filename):
    '''
    function that saves the list of tuples in a csv file
    '''
    with open(filename, mode='w', newline='') as file:
        writer = csv.writer(file)
        writer.writerow('restaurant_id,street,address_number,zip_code,city,province,country'.split(','))
        writer.writerows(addresses)


num_addresses = 10000 #set the number of lines you want
addresses = generate_addresses(num_addresses)
save_to_csv(addresses, 'address_generated.csv')
