--REGULAR CLIENTS
CREATE TABLE IF NOT EXISTS CLIENT
(
    ID INTEGER PRIMARY KEY, 
    GENDER VARCHAR(1) NOT NULL,
    NAME VARCHAR(40) NOT NULL,
    AGE INTEGER NOT NULL,
    FAVORITE_FOOD VARCHAR(45) NOT NULL,
    check(GENDER in ('M', 'F'))
);

--REGULAR FOOD ALLERGY
CREATE TABLE IF NOT EXISTS FOOD_ALLERGY
(
    ID INTEGER PRIMARY KEY,
    FOOD VARCHAR(40) NOT NULL
);

--ASSOCIATE CLIENTS WITH ALLERGIES
CREATE TABLE IF NOT EXISTS CLIENT_ALLERGY
(
    CLIENT_ID INTEGER,
    ALLERGY_ID INTEGER,
    PRIMARY KEY (CLIENT_ID, ALLERGY_ID),
    CONSTRAINT FK_ALLERGY_CLI FOREIGN KEY(CLIENT_ID) REFERENCES CLIENT(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ALLERGY_FOOD FOREIGN KEY(ALLERGY_ID) REFERENCES FOOD_ALLERGY(ID) ON DELETE CASCADE
);
--This is just a PoC no need to add incrementing ID system in any table--

--MOCK DATA
INSERT INTO CLIENT VALUES(2, 'M', 'MARCOS PETRUCCI', 23, 'PASTA AL POMODORO');
INSERT INTO FOOD_ALLERGY VALUES(1, 'SHRIMP');
INSERT INTO FOOD_ALLERGY VALUES(2, 'PEANUT');
INSERT INTO CLIENT_ALLERGY VALUES(2,1);
INSERT INTO CLIENT_ALLERGY VALUES(2,2);
INSERT INTO CLIENT VALUES(3, 'M', 'GIOVANNI A', 23, 'PIZZA');
